version: "3.3"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: php:7.3.30-apache
    ports:
      - "4500:80"
    volumes:
      - ./www:/var/www/html/

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=teste
      - MYSQL_USER=carlos
      - MYSQL_PASSWORD=1234

    volumes:
    - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
